### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by dev89s** [stephenkati/recipe_app#7]
In this project, we are 2 coding partners @dev89s, @stephenkati.

The project task list (Kanban board) could be found [here](https://github.com/stephenkati/recipe_app/projects/1).

It is a recipe app that keeps track of all your recipes and ingredients. It will allow you to save ingredients, and keep track of what you have, and create recipes.

**Comment by Ibizugbe** [comment]
Hi @dev89s  @stephenkati , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] The link to the project has been provided👍🏼.
- [x] The member of the team has been given👍🏼.
- [x] The task is equally distributed at the moment👍🏼.


## Required Changes ♻️

- [ ] Nice Job so far😉. I noticed you didn't add the `General shopping list view` and `n+1 queries` to the tasks in your projects. kindly do well to add them as they are major requirements for this milestone😉. Ensure the tasks in your project takes care of every requirements particular to your team👍🏼 and don't forget to ensure the points are equally distributed😉.
<img width="1015" alt="image" src="https://github.com/stephenkati/recipe_app/assets/64643995/826322c1-7c60-4a92-a72c-b9a7f6d3f9f2">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stephenkati** [comment]
General shopping list does not apply for a team of 2.
Although Generate a shopping list is covered under recipe details

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @dev89s and @stephenkati,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
